### ISSUE TITLE
大佬，问一个问题

### ISSUE THREAD

**Issue by micheallcw** [CncCbz/xybSign#11]
这个校友邦自动打卡可不可以做成圈x的脚本？苹果用户配合快捷指令更方便一些。

**Comment by CncCbz** [comment]
圈x是啥

**Comment by liangw1024** [comment]
大佬，签到提示获取实训人id失败

**Comment by CncCbz** [comment]
python版本吗?python版本已经很久没有维护了,因为我没有账号做测试.

**Comment by CncCbz** [comment]
> 大佬，签到提示获取实训人id失败

python版本吗?python版本已经很久没有维护了,因为我没有账号做测试.

**Comment by micheallcw** [comment]
> 大佬，签到提示获取实训人id失败
我是用php的 可以运行 github里面有 可以参考一下

**Comment by micheallcw** [comment]
> 圈x是啥

Quantumult X
