### ISSUE TITLE
0

### ISSUE THREAD

**Issue by XCQINzs** [CncCbz/xybSign#14]

**Comment by XCQINzs** [comment]
还是只有周报跟月报

**Comment by CncCbz** [comment]
没有账号做签到测试,所以js版本是只有周报的

**Comment by XCQINzs** [comment]
我有账号，老哥方便吗。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月26日(周四) 中午11:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [CncCbz/xybSign] 这个版本有签到吗 (Issue #14)




 
没有账号做签到测试,所以js版本是只有周报的

**Comment by CncCbz** [comment]
加一下qq:1179478342,我看看

**Comment by XCQINzs** [comment]
貌似有



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月26日(周四) 中午11:45
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [CncCbz/xybSign] 这个版本有签到吗 (Issue #14)




 
加一下qq:1179478342,我看看
