### ISSUE TITLE
签到返回位置获取失败

### ISSUE THREAD

**Issue by ybz-ybz** [CncCbz/xybSign#17]
这是啥情况，他这获取地址的方式是怎么回事，是又改了吗

**Comment by CncCbz** [comment]
接口变更,把接口换成备注签到接口

**Comment by ybz-ybz** [comment]
可以了，谢谢

**Comment by qianrena** [comment]
大佬，备注签到接口是什么？能发一下吗？我不太懂这个

**Comment by CncCbz** [comment]
下载最新的代码就可以了

**Comment by qianrena** [comment]
是改用node版本吗？node版也可以腾讯云部署吗？

**Comment by CncCbz** [comment]
nodejs版本是最新的，腾讯云函数应该是可以部署的

**Comment by qianrena** [comment]
我跟着python版本去部署，改了运行环境跟着nodejs版本去终端输入命令以及非调试模式运行文件都打卡成功了。但是点测试跟配置触发器都不能签到，不知道是哪里不对。执行方法改成了index.run

**Comment by qianrena** [comment]
Invoke function yyy [RequestId:4aee824b-7fd6-4f3d-852d-11f6721e00e7]
Response: 
{"key1":"test value 1","key2":"test value 2"}
Output:
START RequestId: 4aee824b-7fd6-4f3d-852d-11f6721e00e7
Event RequestId: 4aee824b-7fd6-4f3d-852d-11f6721e00e7
====当前账号(***)执行结束====
====所有账号执行结束====
### 账号(***) ###
Error: Error: connect ETIMEDOUT 47.110.211.122:443

====当前账号(***)执行结束====
====所有账号执行结束====
### 账号(***) ###
Error: Error: connect ETIMEDOUT 47.110.211.122:443

{ key1: 'test value 1', key2: 'test value 2' }
{
  succeed: [Function: succeed],
  fail: [Function: fail],
  callbackWaitsForEmptyEventLoop: [Getter/Setter],
  getRemainingTimeInMillis: [Function: getRemainingTimeInMillis],
  memory_limit_in_mb: 512,
  time_limit_in_ms: 3000,
  request_id: '4aee824b-7fd6-4f3d-852d-11f6721e00e7',
  environment: '{"SCF_NAMESPACE":"default"}',
  environ: 'SCF_NAMESPACE=default;SCF_NAMESPACE=default',
  function_version: '$LATEST',
  function_name: 'yyy',
  namespace: 'default',
  tencentcloud_region: 'ap-guangzhou',
  tencentcloud_appid: '1323479478',
  tencentcloud_uin: '100034909221'
}
>> 执行登录

END RequestId: 4aee824b-7fd6-4f3d-852d-11f6721e00e7
Report RequestId: 4aee824b-7fd6-4f3d-852d-11f6721e00e7 Duration:3ms Memory:512MB MemUsage:16.0174MB
Summary:
  Request ID: 4aee824b-7fd6-4f3d-852d-11f6721e00e7
  Run Duration: 3
  Bill Duration: 3
  Usage Memory: 16.017440795898438
  Invoke Result: 0

**Comment by qianrena** [comment]
上面是这是测试返回的信息，使用运行和终端返回的是这个：
/usr/local/bin/node ./src/index.js
>> 执行登录
>> 获取任务列表
>> 获取实习项目
>> 执行任务
*签到模式*
 签到
已签到,重新签到
====当前账号(***)执行结束====
====所有账号执行结束====
###***###
签到:
已重新签到
填写周报:
未开启自动填写周报
签到:
签到失败Error: Error: 参数错误

**Comment by qianrena** [comment]
我好像知道是什么问题了，签到是要运行整个js文件，而腾讯的触发器只触发一个函数，于是我去gpt了一段运行整个文件的代码就部署成功了

**Comment by qianrena** [comment]
我好像知道是什么问题了，签到是要运行整个js文件，而腾讯的触发器只触发一个函数，于是我去gpt了一段运行整个文件的代码就成功了，感谢大佬

**Comment by CncCbz** [comment]
腾讯云函数是免费的吗？前段时间好像开始收费了？

**Comment by qianrena** [comment]
新用户免费三个月，过段时间可能要再找类似的免费服务了

**Comment by CncCbz** [comment]
> 新用户免费三个月，过段时间可能要再找类似的免费服务了

我更新了github自动签到的方式，可以尝试一下

**Comment by qianrena** [comment]
> > 新用户免费三个月，过段时间可能要再找类似的免费服务了
> 
> 我更新了github自动签到的方式，可以尝试一下

试了一下发现账号密码那块有问题，我复制粘贴了secrets示例，运行后结果是### 账号(***) ### Error: Error: 账号与密码不匹配，请重新输入 (***)，删掉周报、重新签到配置以及给密码加“”都是如此。而给账号加“”后会返回用户名或密码错误，所以我认为是密码引用那里可能有点问题。再有一个是qmsg酱是发送长串数字是违规的，发不出去的，而账号一般都是手机号，所以消息会违规发不出去

**Comment by CncCbz** [comment]
> > > 新用户免费三个月，过段时间可能要再找类似的免费服务了
> > 
> > 我更新了github自动签到的方式，可以尝试一下
> 
> 试了一下发现账号密码那块有问题，我复制粘贴了secrets示例，运行后结果是### 账号(***) ### Error: Error: 账号与密码不匹配，请重新输入 (***)，删掉周报、重新签到配置以及给密码加“”都是如此。而给账号加“”后会返回用户名或密码错误，所以我认为是密码引用那里可能有点问题。再有一个是qmsg酱是发送长串数字是违规的，发不出去的，而账号一般都是手机号，所以消息会违规发不出去

已修复，感谢反馈
