### ISSUE TITLE
获取当前位置失败

### ISSUE THREAD

**Issue by bilisheep** [CncCbz/xybSign#19]
https://xcx.xybsyw.com:443 "POST /student/clock/Post!autoClock.action HTTP/1.1" 200 202

2023-12-03 17:34:24 获取当前位置失败，请刷新后重试

**Comment by CncCbz** [comment]
查看 #17

**Comment by bilisheep** [comment]
> 查看#17

我发现了这个问题后重新跟了下数据包，发现在现在的数据包中新增了，t（时间戳），m（md5），和s 的http头。服务器会存储这些数据并进行校验。这些数据在前端产生，可通过逆向小程序来获得前端源码。我正在审计相关js，逆向算法，但是比较困难

**Comment by CncCbz** [comment]
node版本已经做了逆向,可以参考 [xyb.js](https://github.com/CncCbz/xybSign/blob/node/utils/xyb.js)

**Comment by bilisheep** [comment]
相关js如下

> node版本已经做了逆向，可以参考[xyb.js](https://github.com/CncCbz/xybSign/blob/node/utils/xyb.js)

牛逼，言简意赅
