### ISSUE TITLE
两个用户这样写怎么不行啊

### ISSUE THREAD

**Issue by Liyff** [CncCbz/xybSign#30]
例如：username=用户名1&password=密码1;username=用户名2&password=密码2&reSign=true&needReport=true；mode=in;qmsgKey=keykey;qmsgTo=123412445

**Comment by CncCbz** [comment]
把 运行日志 和 去除个人信息的secret 发一下

**Comment by Liyff** [comment]
![image](https://github.com/CncCbz/xybSign/assets/100138334/b519f937-c1f3-4753-8c1a-e9709af8824b)
username=1111&password=521;
username=2222&password=725;
mode=in;qmsgKey=e5cefb5b6c86fdfc67;qmsgTo=123456789

**Comment by CncCbz** [comment]
secret不要换行试一下

**Comment by Liyff** [comment]
可以了，感谢
