### ISSUE TITLE
本地运行无法签到

### ISSUE THREAD

**Issue by misukus** [CncCbz/xybSign#32]
根据步骤部署在电脑，修改了config文件后运行，提示可以登录但无法签到，请问大佬还需要修改哪一部分？
![16ce96a4144cd3cb4a8534345058898](https://github.com/CncCbz/xybSign/assets/57579742/9fa4f633-a893-4099-a4cb-44d52afef791)
![79b6be5dde321ca368a7e02041e0b98](https://github.com/CncCbz/xybSign/assets/57579742/f2f503fc-3a28-41eb-bfea-84d2c88b9e7a)

**Comment by CncCbz** [comment]
校友邦上有几个实习任务？

**Comment by misukus** [comment]
这样的![image](https://github.com/CncCbz/xybSign/assets/57579742/353fa36b-15b2-431b-bd68-08a921ff8d15)

**Comment by CncCbz** [comment]
https://xybfreesign.netlify.app/
麻烦你去这个网站试一下能不能签到，我定位一下问题

**Comment by misukus** [comment]
![image](https://github.com/CncCbz/xybSign/assets/57579742/0e7bed2d-e7c7-455e-8c0b-93ee7665fc47)
网站上是可以正确获取到实习任务的

**Comment by CncCbz** [comment]
有在微信小程序校友邦上绑定过你的校友邦账号吗？

**Comment by misukus** [comment]
你好，有绑定的

**Comment by CncCbz** [comment]
应该是获取 签到表单`getClockInfo`这个函数出了问题，你可以加日志调试看一下问题出在哪。或者提供一下你的账号用于调试

**Comment by misukus** [comment]
大佬怎么提供账号到您呢

**Comment by CncCbz** [comment]
加一下qq：1179478342
