### ISSUE TITLE
大佬大佬，如果有服务器，怎么在服务器上用计划任务执行？实现自动签到？

### ISSUE THREAD

**Issue by hanyan666** [CncCbz/xybSign#33]
大佬大佬，如果有服务器，怎么在服务器上用计划任务执行？实现自动签到？

**Comment by CncCbz** [comment]
按照`本地运行`的方式在服务器上拉取代码，然后用`Crontab `创建定时任务，运行`index.js`文件

**Comment by hanyan666** [comment]
大佬再问一下，服务器是用win还是centos?我用centos安装了nodejs,但是执行npm install 一直错误。

**Comment by CncCbz** [comment]
都可以，npm install报错看下是不是网络问题

**Comment by NDK2992926355** [comment]
> 都可以，npm install报错看下是不是网络问题

大佬我这里显示网关错误

**Comment by CncCbz** [comment]
贴下日志看下

**Comment by NDK2992926355** [comment]
> 贴下日志看下

Error: AxiosError: Request failed with statu s code 502 一就是用你网站签到的

**Comment by CncCbz** [comment]
这是xyb小程序崩了，等xyb修复，晚点再试试

**Comment by NDK2992926355** [comment]
> 这是xyb小程序崩了，等xyb修复

刚刚可以了，谢谢

**Comment by NDK2992926355** [comment]
> 这是xyb小程序崩了，等xyb修复

感谢大佬

**Comment by hanyan666** [comment]
大佬，我在服务器安装的win系统，安装了nodejs,成功签到了。怎么让它自动签到？用Crontab 吗？怎么使用？

**Comment by CncCbz** [comment]
用win自带的定时任务就可以了，参考gpt给出的步骤
![image](https://github.com/CncCbz/xybSign/assets/43227065/9acd3275-248f-4862-94d6-03e0ef675731)

**Comment by hanyan666** [comment]
已经弄好了，谢谢大佬。
