### ISSUE TITLE
签退代码有问题，无法签退

### ISSUE THREAD

**Issue by LuxChan** [CncCbz/xybSign#4]
修改outtime为intime似乎可行，望解决

**Comment by LuxChan** [comment]
另外消息推送接口似乎也是失效的，填入key也无法推送

**Comment by DJJ007** [comment]
> 修改outtime为intime似乎可行，望解决

改成in那就是签退了

**Comment by DJJ007** [comment]
> 修改outtime为intime似乎可行，望解决

改成in那就是签到了

**Comment by LuxChan** [comment]
> > 修改outtime为intime似乎可行，望解决
> 
> 改成in那就是签到了

没，改成intime就可以正常签退签到
