### ISSUE TITLE
学习

### ISSUE THREAD

**Issue by Huang0666** [CncCbz/xybSign#42]
作者大大 如何从0-1手搓这个项目？想作为学习经历

**Comment by CncCbz** [comment]
从逆向分析登录接口的加密开始

**Comment by Huang0666** [comment]
我需要前驱知识？还是边了解边学习？

**Comment by Huang0666** [comment]
这个属于那个方面的范畴？

**Comment by Huang0666** [comment]
我在这方面属于纯小白，了解的较少，应该往js/爬虫方面学习？

**Comment by CncCbz** [comment]
差不多吧，就是js逆向和爬虫。如果你是想成为程序员，这个项目对你帮助不大

**Comment by Huang0666** [comment]
好的，作者目前已经工作了？ 出于兴趣哈哈

**Comment by CncCbz** [comment]
已工作。出于兴趣的话，可以先从js逆向学起，如果有代码基础，应该不算很难
