### ISSUE TITLE
请问本地部署，多个账户签到，为什么只签上了一个？

### ISSUE THREAD

**Issue by xLeeCo** [CncCbz/xybSign#45]
![92b47e1ed2b4c98c16cf7a197f957661](https://github.com/user-attachments/assets/991cd66e-982f-45d0-9b41-cae955326f6a)
![b453ddca0f9e1d72784ef55640276b63](https://github.com/user-attachments/assets/713ab4c6-d9d0-4c66-af53-0959f395146f)

**Comment by CncCbz** [comment]
把 // 去掉，你把他注释了当然不运行。。。
![image](https://github.com/user-attachments/assets/e9c59103-c3e3-4df6-97aa-56765a4e7a34)

**Comment by xLeeCo** [comment]
谢谢谢谢，刚发现有注释
