### ISSUE TITLE
如果有空可以修复一下重新签到请求失败问题

### ISSUE THREAD

**Issue by PBK-B** [CncCbz/xybSign#9]
@CncCbz 如果有空帮忙修复一下重新签到请求失败问题，请求加密我已经分析完了 <https://bin.zmide.com/?p=1078>，我 Python 能力较弱不然自己提 PR 了 🙈

**Comment by CncCbz** [comment]
其实一直想更新,但是没有由于已经毕业,没有可用于调试的账号,所以一直搁置了😼.
可以看看其他人的项目是否已解决这个问题

**Comment by PBK-B** [comment]
> 其实一直想更新,但是没有由于已经毕业,没有可用于调试的账号,所以一直搁置了😼. 可以看看其他人的项目是否已解决这个问题

要不我这边联系一下你，帮你弄个账号调试一下？email: bin@PBK6.cn
